#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions



rm -rf processor*
rm elapsed_time

rm -rf [1-9]*
rm -rf 0.*
rm 0/cellDist
rm 0/phi
rm constant/geometry/*.eMesh

rm log.*
#------------------------------------------------------------------------------
