#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

python3 elapsed_time.py

runApplication surfaceFeatures
runApplication blockMesh
runApplication decomposePar -cellDist
runParallel snappyHexMesh -overwrite
runApplication reconstructParMesh -constant -cellDist
runApplication reconstructPar -latestTime

: '
runParallel extrudeMesh
#runParallel patchSummary
runParallel $(getApplication)
runApplication reconstructParMesh -cellDist
runApplication reconstructPar
'

#: '
runApplication extrudeMesh
runApplication patchSummary
runApplication $(getApplication)
#'
python3 elapsed_time.py
#------------------------------------------------------------------------------
