#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

python3 elapsed_time.py

runApplication surfaceFeatures
runApplication blockMesh
runApplication decomposePar -copyZero -cellDist
runParallel snappyHexMesh
runApplication reconstructParMesh -constant -cellDist

python3 elapsed_time.py
#------------------------------------------------------------------------------
